{{
    config (
      engine='MergeTree()',
      order_by=['POS_ID','POS_POS_NUM','INV_POS_NUM', 'CREATED_DTTM'],
	  unique_key=['POS_ID', 'INV_CD', 'INV_POS_NUM', 'CREATED_DTTM']
    )
}}

{% if is_incremental() %}

  with tmp as (
    select 	if(t1.POS_ID>t2.POS_ID,t1.POS_ID,t2.POS_ID) as POS_ID,
			if(t1.POS_POS_NUM>t2.POS_POS_NUM,t1.POS_POS_NUM,t2.POS_POS_NUM) as POS_POS_NUM,
			if(t1.INV_CD>t2.INV_CD,t1.INV_CD,t2.INV_CD) as INV_CD,
			if(t1.INV_POS_NUM>t2.INV_POS_NUM,t1.INV_POS_NUM,t2.INV_POS_NUM) as INV_POS_NUM,
			if(t1.PRODUCT_ID>t2.PRODUCT_ID,t1.PRODUCT_ID,t2.PRODUCT_ID) as PRODUCT_ID,
			if(t1.PICKUP_STORE_LOC_ID>t2.PICKUP_STORE_LOC_ID,t1.PICKUP_STORE_LOC_ID,t2.PICKUP_STORE_LOC_ID) as PICKUP_STORE_LOC_ID,
			if(t1.PICKUP_DT>t2.PICKUP_DT,t1.PICKUP_DT,t2.PICKUP_DT) as PICKUP_DT,
			if(t1.SERVICE_FLG>t2.SERVICE_FLG,t1.SERVICE_FLG,t2.SERVICE_FLG) as SERVICE_FLG,
			if(t1.INV_DT>t2.INV_DT,t1.INV_DT,t2.INV_DT) as INV_DT,
			if(t1.OPERATION_TYPE>t2.OPERATION_TYPE,t1.OPERATION_TYPE,t2.OPERATION_TYPE) as OPERATION_TYPE,
			if(t1.ORIG_POS_ID>t2.ORIG_POS_ID,t1.ORIG_POS_ID,t2.ORIG_POS_ID) as ORIG_POS_ID,
			if(t1.ORIG_POS_POS_NUM>t2.ORIG_POS_POS_NUM,t1.ORIG_POS_POS_NUM,t2.ORIG_POS_POS_NUM) as ORIG_POS_POS_NUM,
			if(t1.STORNO_INV_CD>t2.STORNO_INV_CD,t1.STORNO_INV_CD,t2.STORNO_INV_CD) as STORNO_INV_CD,
			if(t1.UNIT>t2.UNIT,t1.UNIT,t2.UNIT) as UNIT,
			if(t1.COST>t2.COST,t1.COST,t2.COST) as COST,
			if(t1.COST_PRODUCT>t2.COST_PRODUCT,t1.COST_PRODUCT,t2.COST_PRODUCT) as COST_PRODUCT,
			if(t1.COST_FREIGHT>t2.COST_FREIGHT,t1.COST_FREIGHT,t2.COST_FREIGHT) as COST_FREIGHT,
			if(t1.COST_DELIVERY>t2.COST_DELIVERY,t1.COST_DELIVERY,t2.COST_DELIVERY) as COST_DELIVERY,
			if(t1.SALES_QTY>t2.SALES_QTY,t1.SALES_QTY,t2.SALES_QTY) as SALES_QTY,
			if(t1.UNIT_BASE>t2.UNIT_BASE,t1.UNIT_BASE,t2.UNIT_BASE) as UNIT_BASE,
			if(t1.SALES_QTY_BASE>t2.SALES_QTY_BASE,t1.SALES_QTY_BASE,t2.SALES_QTY_BASE) as SALES_QTY_BASE,
			if(t1.REVENUE>t2.REVENUE,t1.REVENUE,t2.REVENUE) as REVENUE,
			if(t1.REVENUE_WITH_VAT>t2.REVENUE_WITH_VAT,t1.REVENUE_WITH_VAT,t2.REVENUE_WITH_VAT) as REVENUE_WITH_VAT,
			if(t1.DISCOUNT_CARD>t2.DISCOUNT_CARD,t1.DISCOUNT_CARD,t2.DISCOUNT_CARD) as DISCOUNT_CARD,
			if(t1.CREATED_DTTM>t2.CREATED_DTTM,t1.CREATED_DTTM,t2.CREATED_DTTM) as CREATED_DTTM,
			if(t1.MODIFIED_DTTM>t2.MODIFIED_DTTM,t1.MODIFIED_DTTM,t2.MODIFIED_DTTM) as MODIFIED_DTTM,
			if(t1.CREATED_PCS_ID>t2.CREATED_PCS_ID,t1.CREATED_PCS_ID,t2.CREATED_PCS_ID) as CREATED_PCS_ID,
			if(t1.MODIFIED_PCS_ID>t2.MODIFIED_PCS_ID,t1.MODIFIED_PCS_ID,t2.MODIFIED_PCS_ID) as MODIFIED_PCS_ID,
			if(t1.DELETE_FLG>t2.DELETE_FLG,t1.DELETE_FLG,t2.DELETE_FLG) as DELETE_FLG
	from {{ ref('stg_pos_body') }} as t1 
	full join {{ this }} as t2
	on t1.POS_ID = t2.POS_ID 
	and t1.INV_CD = t2.INV_CD
	and t1.INV_POS_NUM = t2.INV_POS_NUM
	and t1.CREATED_DTTM = t2.CREATED_DTTM
  )

{% else %}

  with tmp as (
    select *
	from {{ ref('stg_pos_body') }} 
)

{% endif %}

select *
from tmp