{{
    config (
      engine='MergeTree()',
      order_by=['PRODUCT_ID', 'STORE_LOCATION_ID', 'PERIOD_START_DT', 'PRICE_TYPE_ID', 'CREATED_DTTM'],
	  unique_key=['PRODUCT_ID', 'STORE_LOCATION_ID', 'PERIOD_START_DT', 'PRICE_TYPE_ID', 'CREATED_DTTM']
    )
}}

{% if is_incremental() %}

  with tmp as (
    select 	if(t1.PRODUCT_ID>t2.PRODUCT_ID,t1.PRODUCT_ID,t2.PRODUCT_ID) as PRODUCT_ID,
			if(t1.STORE_LOCATION_ID>t2.STORE_LOCATION_ID,t1.STORE_LOCATION_ID,t2.STORE_LOCATION_ID) as STORE_LOCATION_ID,
			if(t1.PERIOD_START_DT>t2.PERIOD_START_DT,t1.PERIOD_START_DT,t2.PERIOD_START_DT) as PERIOD_START_DT,
			if(t1.PERIOD_END_DT>t2.PERIOD_END_DT,t1.PERIOD_END_DT,t2.PERIOD_END_DT) as PERIOD_END_DT,
			if(t1.PRICE>t2.PRICE,t1.PRICE,t2.PRICE) as PRICE,
			if(t1.UNIT>t2.UNIT,t1.UNIT,t2.UNIT) as UNIT,
			if(t1.PRICE_TYPE_ID>t2.PRICE_TYPE_ID,t1.PRICE_TYPE_ID,t2.PRICE_TYPE_ID) as PRICE_TYPE_ID,
			if(t1.CREATED_DTTM>t2.CREATED_DTTM,t1.CREATED_DTTM,t2.CREATED_DTTM) as CREATED_DTTM,
			if(t1.MODIFIED_DTTM>t2.MODIFIED_DTTM,t1.MODIFIED_DTTM,t2.MODIFIED_DTTM) as MODIFIED_DTTM,
			if(t1.CREATED_PCS_ID>t2.CREATED_PCS_ID,t1.CREATED_PCS_ID,t2.CREATED_PCS_ID) as CREATED_PCS_ID,
			if(t1.MODIFIED_PCS_ID>t2.MODIFIED_PCS_ID,t1.MODIFIED_PCS_ID,t2.MODIFIED_PCS_ID) as MODIFIED_PCS_ID,
			if(t1.DELETE_FLG>t2.DELETE_FLG,t1.DELETE_FLG,t2.DELETE_FLG) as DELETE_FLG
	from {{ ref('stg_price') }} as t1 
	full join {{ this }} as t2
	on t1.PRODUCT_ID = t2.PRODUCT_ID 
	and t1.STORE_LOCATION_ID = t2.STORE_LOCATION_ID
	and t1.PERIOD_START_DT = t2.PERIOD_START_DT
	and t1.PRICE_TYPE_ID = t2.PRICE_TYPE_ID
	and t1.CREATED_DTTM = t2.CREATED_DTTM
  )

{% else %}

  with tmp as (
    select *
	from {{ ref('stg_price') }} 
)

{% endif %}

select *
from tmp