{{
    config (
      engine='MergeTree()',
      order_by=['POS_ID', 'POS_POS_NUM', 'PRODUCT_ID', 'PROMO_ID', 'CREATED_DTTM'],
	  unique_key=['POS_ID', 'POS_POS_NUM', 'PRODUCT_ID', 'PROMO_ID', 'CREATED_DTTM']
    )
}}

{% if is_incremental() %}

  with tmp as (
    select 	if(t1.POS_ID>t2.POS_ID,t1.POS_ID,t2.POS_ID) as POS_ID,
			if(t1.POS_POS_NUM>t2.POS_POS_NUM,t1.POS_POS_NUM,t2.POS_POS_NUM) as POS_POS_NUM,
			if(t1.PRODUCT_ID>t2.PRODUCT_ID,t1.PRODUCT_ID,t2.PRODUCT_ID) as PRODUCT_ID,
			if(t1.PROMO_ID>t2.PROMO_ID,t1.PROMO_ID,t2.PROMO_ID) as PROMO_ID,
			if(t1.PRIORITY_NUM>t2.PRIORITY_NUM,t1.PRIORITY_NUM,t2.PRIORITY_NUM) as PRIORITY_NUM,
			if(t1.PRICE_ACCUMULATED>t2.PRICE_ACCUMULATED   ,t1.PRICE_ACCUMULATED,t2.PRICE_ACCUMULATED) as PRICE_ACCUMULATED,
			if(t1.DELTA_DISCOUNT>t2.DELTA_DISCOUNT,t1.DELTA_DISCOUNT,t2.DELTA_DISCOUNT) as DELTA_DISCOUNT,
			if(t1.CREATED_DTTM>t2.CREATED_DTTM,t1.CREATED_DTTM,t2.CREATED_DTTM) as CREATED_DTTM,
			if(t1.MODIFIED_DTTM>t2.MODIFIED_DTTM,t1.MODIFIED_DTTM,t2.MODIFIED_DTTM) as MODIFIED_DTTM,
			if(t1.CREATED_PCS_ID>t2.CREATED_PCS_ID,t1.CREATED_PCS_ID,t2.CREATED_PCS_ID) as CREATED_PCS_ID,
			if(t1.MODIFIED_PCS_ID>t2.MODIFIED_PCS_ID,t1.MODIFIED_PCS_ID,t2.MODIFIED_PCS_ID) as MODIFIED_PCS_ID,
			if(t1.DELETE_FLG>t2.DELETE_FLG,t1.DELETE_FLG,t2.DELETE_FLG) as DELETE_FLG
	from {{ ref('stg_promo_pos') }} as t1 
	full join {{ this }} as t2
	on t1.POS_ID = t2.POS_ID 
	and t1.POS_POS_NUM = t2.POS_POS_NUM
	and t1.PRODUCT_ID = t2.PRODUCT_ID
	and t1.PROMO_ID = t2.PROMO_ID
	and t1.CREATED_DTTM = t2.CREATED_DTTM
  )

{% else %}

  with tmp as (
    select *
	from {{ ref('stg_promo_pos') }} 
)

{% endif %}

select *
from tmp