{{
    config (
      engine='MergeTree()',
      order_by=['PRODUCT_ID', 'CREATED_DTTM'],
	  unique_key=['PRODUCT_ID', 'CREATED_DTTM']
    )
}}

{% if is_incremental() %}

  with tmp as (
    select 	if(t1.PRODUCT_ID>t2.PRODUCT_ID,t1.PRODUCT_ID,t2.PRODUCT_ID) as PRODUCT_ID,
			if(t1.PRODUCT_CD>t2.PRODUCT_CD,t1.PRODUCT_CD,t2.PRODUCT_CD) as PRODUCT_CD,
			if(t1.PRODUCT_NM>t2.PRODUCT_NM,t1.PRODUCT_NM,t2.PRODUCT_NM) as PRODUCT_NM,
			if(t1.RT_CD>t2.RT_CD,t1.RT_CD,t2.RT_CD) as RT_CD,
			if(t1.RT_NM>t2.RT_NM,t1.RT_NM,t2.RT_NM) as RT_NM,
			if(t1.PRODUCT_LVL_ID1>t2.PRODUCT_LVL_ID1,t1.PRODUCT_LVL_ID1,t2.PRODUCT_LVL_ID1) as PRODUCT_LVL_ID1,
			if(t1.PRODUCT_LVL_CD1>t2.PRODUCT_LVL_CD1,t1.PRODUCT_LVL_CD1,t2.PRODUCT_LVL_CD1) as PRODUCT_LVL_CD1,
			if(t1.PRODUCT_LVL_NM1>t2.PRODUCT_LVL_NM1,t1.PRODUCT_LVL_NM1,t2.PRODUCT_LVL_NM1) as PRODUCT_LVL_NM1,
			if(t1.PRODUCT_LVL_ID2>t2.PRODUCT_LVL_ID2,t1.PRODUCT_LVL_ID2,t2.PRODUCT_LVL_ID2) as PRODUCT_LVL_ID2,
			if(t1.PRODUCT_LVL_CD2>t2.PRODUCT_LVL_CD2,t1.PRODUCT_LVL_CD2,t2.PRODUCT_LVL_CD2) as PRODUCT_LVL_CD2,
			if(t1.PRODUCT_LVL_NM2>t2.PRODUCT_LVL_NM2,t1.PRODUCT_LVL_NM2,t2.PRODUCT_LVL_NM2) as PRODUCT_LVL_NM2,
			if(t1.PRODUCT_LVL_ID3>t2.PRODUCT_LVL_ID3,t1.PRODUCT_LVL_ID3,t2.PRODUCT_LVL_ID3) as PRODUCT_LVL_ID3,
			if(t1.PRODUCT_LVL_CD3>t2.PRODUCT_LVL_CD3,t1.PRODUCT_LVL_CD3,t2.PRODUCT_LVL_CD3) as PRODUCT_LVL_CD3,
			if(t1.PRODUCT_LVL_NM3>t2.PRODUCT_LVL_NM3,t1.PRODUCT_LVL_NM3,t2.PRODUCT_LVL_NM3) as PRODUCT_LVL_NM3,
			if(t1.PRODUCT_LVL_ID4>t2.PRODUCT_LVL_ID4,t1.PRODUCT_LVL_ID4,t2.PRODUCT_LVL_ID4) as PRODUCT_LVL_ID4,
			if(t1.PRODUCT_LVL_CD4>t2.PRODUCT_LVL_CD4,t1.PRODUCT_LVL_CD4,t2.PRODUCT_LVL_CD4) as PRODUCT_LVL_CD4,
			if(t1.PRODUCT_LVL_NM4>t2.PRODUCT_LVL_NM4,t1.PRODUCT_LVL_NM4,t2.PRODUCT_LVL_NM4) as PRODUCT_LVL_NM4,
			if(t1.CREATED_DTTM>t2.CREATED_DTTM,t1.CREATED_DTTM,t2.CREATED_DTTM) as CREATED_DTTM,
			if(t1.MODIFIED_DTTM>t2.MODIFIED_DTTM,t1.MODIFIED_DTTM,t2.MODIFIED_DTTM) as MODIFIED_DTTM,
			if(t1.CREATED_PCS_ID>t2.CREATED_PCS_ID,t1.CREATED_PCS_ID,t2.CREATED_PCS_ID) as CREATED_PCS_ID,
			if(t1.MODIFIED_PCS_ID>t2.MODIFIED_PCS_ID,t1.MODIFIED_PCS_ID,t2.MODIFIED_PCS_ID) as MODIFIED_PCS_ID,
			if(t1.HASH_VAL>t2.HASH_VAL,t1.HASH_VAL,t2.HASH_VAL) as HASH_VAL
	from {{ ref('stg_product') }} as t1 
	full join {{ this }} as t2
	on t1.PRODUCT_ID = t2.PRODUCT_ID 
	and t1.CREATED_DTTM = t2.CREATED_DTTM
  )

{% else %}

  with tmp as (
    select *
	from {{ ref('stg_product') }} 
)

{% endif %}

select *
from tmp