version: 2

sources:

    - name: projdb
      # database: db
      schema: otusproj
      tags: ["projdb"]      
      # freshness:
      #   warn_after: {count: 12, period: hour}
      #   error_after: {count: 24, period: hour}
      # loaded_at_field: created_at
      loader: S3
      description: "External tables"

      tables:

        - name: IN_PRODUCT
          identifier: SRC_PRODUCT

        - name: IN_STORE_LOCATION
          identifier: SRC_STORE_LOCATION

        - name: IN_STORE_LOC_ATTR
          identifier: SRC_STORE_LOC_ATTR

        - name: IN_PRICE
          identifier: SRC_PRICE
          
        - name: IN_PRICE_TYPE
          identifier: SRC_PRICE_TYPE

        - name: IN_PROMO
          identifier: SRC_PROMO

        - name: IN_POS_HEAD
          identifier: SRC_POS_HEAD

        - name: IN_PROMO_POS
          identifier: SRC_PROMO_POS
          
        - name: IN_POS_BODY
          identifier: SRC_POS_BODY

        - name: IN_STOCK
          identifier: SRC_STOCK