{{
    config (
      engine='MergeTree()',
      order_by=['STORE_LOCATION_ID', 'PROMO_TYPE_ID', 'CALDAY_BEFORE', 'CALDAY_CURR'],
	  unique_key=['STORE_LOCATION_ID', 'PROMO_TYPE_ID', 'CALDAY_BEFORE', 'CALDAY_CURR']
    )
}}

with tmp_daily_pos_before_1 as (
SELECT
	T1.STORE_LOCATION_ID as STORE_LOCATION_ID
	,T1.PRODUCT_ID as PRODUCT_ID
	,T1.DATE as TMP_CALDAY_BEFORE
	,date_add(YEAR, 1, T1.DATE) as TMP_CALDAY_CURR
	,(SUM(T1.SALES_QTY)) as SALES_QTY
	,(SUM(T1.COST)) as COST
	,(SUM(T1.REVENUE)) as REVENUE
	,(SUM(T1.VAT)) as VAT
FROM otusproj.tmp_daily_pos AS T1
INNER JOIN otusproj.tmp_daily_pos_flg AS T2
	ON T1.PRODUCT_ID = T2.PRODUCT_ID
	AND T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
	AND T2.DATE_CURR = toStartOfMonth(date_add(YEAR, 1, T1.DATE))
WHERE T1.PERIOD_TYPE = 'BEFORE'
GROUP BY T1.STORE_LOCATION_ID
	, T1.PRODUCT_ID
	, TMP_CALDAY_BEFORE
	, TMP_CALDAY_CURR
),

tmp_daily_pos_before_2 as (
SELECT
	T1.STORE_LOCATION_ID as STORE_LOCATION_ID
	,T1.PRODUCT_ID as PRODUCT_ID
	,T2.PROMO_TYPE_ID as PROMO_TYPE_ID
	,T2.CNT_ORD_BY_PROMO as CNT_ORD_BY_PROMO
	,T3.CNT_ORD_ON_DAY as CNT_ORD_ON_DAY
	,T1.TMP_CALDAY_BEFORE as TMP_CALDAY_BEFORE
	,T1.TMP_CALDAY_CURR as TMP_CALDAY_CURR
	,SUM(T1.SALES_QTY)*if(T2.CNT_ORD_BY_PROMO>0,T2.CNT_ORD_BY_PROMO,1)/if(T3.CNT_ORD_ON_DAY>0,T3.CNT_ORD_ON_DAY,1) AS SALES_QTY
	,SUM(T1.COST)*if(T2.CNT_ORD_BY_PROMO>0,T2.CNT_ORD_BY_PROMO,1)/if(T3.CNT_ORD_ON_DAY>0,T3.CNT_ORD_ON_DAY,1) AS COST
	,SUM(T1.REVENUE)*if(T2.CNT_ORD_BY_PROMO>0,T2.CNT_ORD_BY_PROMO,1)/if(T3.CNT_ORD_ON_DAY>0,T3.CNT_ORD_ON_DAY,1) AS REVENUE
	,SUM(T1.VAT)*if(T2.CNT_ORD_BY_PROMO>0,T2.CNT_ORD_BY_PROMO,1)/if(T3.CNT_ORD_ON_DAY>0,T3.CNT_ORD_ON_DAY,1) AS VAT
FROM tmp_daily_pos_before_1 AS T1
LEFT JOIN otusproj.tmp_daily_promo_curr AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
	AND T1.PRODUCT_ID = T2.PRODUCT_ID
	AND toStartOfMonth(T1.TMP_CALDAY_CURR) = T2.DATE_CURR
LEFT JOIN otusproj.tmp_daily_total_curr AS T3
	ON T1.STORE_LOCATION_ID = T3.STORE_LOCATION_ID
	AND T1.PRODUCT_ID = T3.PRODUCT_ID
	AND toStartOfMonth(T1.TMP_CALDAY_CURR) = T3.DATE_CURR
GROUP BY T1.STORE_LOCATION_ID
	, T1.PRODUCT_ID
	, T2.PROMO_TYPE_ID
	, T2.CNT_ORD_BY_PROMO
	, T3.CNT_ORD_ON_DAY
	, T1.TMP_CALDAY_BEFORE
	, T1.TMP_CALDAY_CURR
),

tmp_daily_pos_before_3 as (
SELECT
	STORE_LOCATION_ID
	,PROMO_TYPE_ID
	,toStartOfMonth(TMP_CALDAY_BEFORE) AS CALDAY_BEFORE
	,toStartOfMonth(TMP_CALDAY_CURR) AS CALDAY_CURR
	,SUM(SALES_QTY) AS SALES_QTY
	,SUM(COST) AS COST
	,SUM(REVENUE) AS REVENUE
	,SUM(VAT) AS VAT
FROM tmp_daily_pos_before_2
GROUP BY STORE_LOCATION_ID
	, PROMO_TYPE_ID
	, CALDAY_BEFORE
	, CALDAY_CURR
)

SELECT
	T1.STORE_LOCATION_ID as STORE_LOCATION_ID
	,T1.PROMO_TYPE_ID as PROMO_TYPE_ID
	,T1.CALDAY_BEFORE as CALDAY_BEFORE
	,T1.CALDAY_CURR as CALDAY_CURR
	,SUM(T1.SALES_QTY) as SALES_QTY
	,SUM(T1.COST) as COST
	,SUM(T1.REVENUE) as REVENUE
	,SUM(T1.VAT) as VAT
	,SUM(T1.REVENUE)/SUM(T1.SALES_QTY) as PRICE_UNIT
	,SUM(T1.COST)/SUM(T1.SALES_QTY) as COST_UNIT
	,SUM(T2.CNT_ORD) as CNT_ORD
FROM tmp_daily_pos_before_3 AS T1
LEFT JOIN otusproj.tmp_cnt_promo_before AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
	AND T1.PROMO_TYPE_ID = T2.PROMO_TYPE_ID
	AND T1.CALDAY_BEFORE = T2.DATE_BEFORE
WHERE T1.SALES_QTY > 0
GROUP BY T1.STORE_LOCATION_ID
	, T1.PROMO_TYPE_ID
	, T1.CALDAY_BEFORE
	, T1.CALDAY_CURR