{{
    config (
      engine='MergeTree()',
      order_by=['STORE_LOCATION_ID','PROMO_TYPE_ID', 'DATE_CURR'],
	  unique_key=['STORE_LOCATION_ID','PROMO_TYPE_ID', 'DATE_CURR']
    )
}}

SELECT DISTINCT T1.STORE_LOCATION_ID as STORE_LOCATION_ID, T1.PROMO_TYPE_ID as PROMO_TYPE_ID
	,T2.DATE_CURR as DATE_CURR
	,toInt32(COUNT(DISTINCT(T1.POS_ID))) as CNT_ORD
FROM otusproj.tmp_daily_pos AS T1
INNER JOIN otusproj.tmp_daily_pos_flg AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID 
	AND T1.PRODUCT_ID = T2.PRODUCT_ID
	AND T2.DATE_CURR = toStartOfMonth(T1.DATE)
	AND T1.PERIOD_TYPE = 'CURR'
GROUP BY T1.STORE_LOCATION_ID
	,T1.PROMO_TYPE_ID
	,T2.DATE_CURR