{{
    config (
      engine='MergeTree()',
      order_by=['PRODUCT_ID', 'STORE_LOCATION_ID', 'DATE_CURR'],
	  unique_key=['PRODUCT_ID', 'STORE_LOCATION_ID', 'DATE_CURR']
    )
}}

SELECT 
	if(A.PRODUCT_ID>B.PRODUCT_ID,A.PRODUCT_ID,B.PRODUCT_ID) AS PRODUCT_ID
	, if(A.STORE_LOCATION_ID>B.STORE_LOCATION_ID,A.STORE_LOCATION_ID,B.STORE_LOCATION_ID) AS STORE_LOCATION_ID
	, if(B.DATE>date_add(YEAR, 1, A.DATE),B.DATE, date_add(YEAR, 1, A.DATE)) AS DATE_CURR
	, CASE WHEN A.PRODUCT_ID < B.PRODUCT_ID THEN 0
		   WHEN A.PRODUCT_ID > B.PRODUCT_ID THEN -1
		   ELSE 1 END AS BEFORE_CURR_FLG
FROM (	SELECT DISTINCT PRODUCT_ID, STORE_LOCATION_ID, 
					toStartOfMonth(DATE) AS DATE
		FROM otusproj.tmp_daily_pos
		WHERE PERIOD_TYPE = 'BEFORE' 
		) AS A
FULL JOIN (	SELECT DISTINCT PRODUCT_ID, STORE_LOCATION_ID, 
					toStartOfMonth(DATE) AS DATE
			FROM otusproj.tmp_daily_pos
			WHERE PERIOD_TYPE = 'CURR' 
		) AS B
	ON A.STORE_LOCATION_ID = B.STORE_LOCATION_ID 
	AND A.PRODUCT_ID = B.PRODUCT_ID 
	AND date_add(YEAR, 1, A.DATE) = B.DATE