{{
    config (
      engine='MergeTree()',
      order_by=['STORE_LOCATION_ID','PROMO_TYPE_ID', 'DATE_BEFORE'],
	  unique_key=['STORE_LOCATION_ID','PROMO_TYPE_ID', 'DATE_BEFORE']
    )
}}

with tmp_cnt_promo_before_1 as (
SELECT DISTINCT T1.STORE_LOCATION_ID as STORE_LOCATION_ID, T3.PROMO_TYPE_ID as PROMO_TYPE_ID
	,toStartOfMonth(T1.DATE) as DATE_BEFORE
	,T3.CNT_ORD_BY_PROMO as CNT_ORD_BY_PROMO
	,T4.CNT_ORD_ON_DAY as CNT_ORD_ON_DAY
	,COUNT(DISTINCT(T1.POS_ID))*if(T3.CNT_ORD_BY_PROMO>0,T3.CNT_ORD_BY_PROMO,1)/if(T4.CNT_ORD_ON_DAY>0,T4.CNT_ORD_ON_DAY,1) AS CNT_ORD
FROM otusproj.tmp_daily_pos AS T1
INNER JOIN otusproj.tmp_daily_pos_flg AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID 
	AND T1.PRODUCT_ID = T2.PRODUCT_ID
	AND T2.DATE_CURR = toStartOfMonth(date_add(YEAR, 1, T1.DATE))
	AND T1.PERIOD_TYPE = 'BEFORE'
LEFT JOIN otusproj.tmp_daily_promo_curr AS T3
	ON T1.STORE_LOCATION_ID = T3.STORE_LOCATION_ID
	AND T1.PRODUCT_ID = T3.PRODUCT_ID
	AND T2.DATE_CURR = T3.DATE_CURR
LEFT JOIN otusproj.tmp_daily_total_curr AS T4
	ON T1.STORE_LOCATION_ID = T4.STORE_LOCATION_ID
	AND T1.PRODUCT_ID = T4.PRODUCT_ID
	AND T2.DATE_CURR = T4.DATE_CURR
GROUP BY T1.STORE_LOCATION_ID
	,T3.PROMO_TYPE_ID
	,DATE_BEFORE
	,T3.CNT_ORD_BY_PROMO
	,T4.CNT_ORD_ON_DAY
),

tmp_cnt_promo_before_2 as (
SELECT T1.STORE_LOCATION_ID as STORE_LOCATION_ID, T1.PROMO_TYPE_ID as PROMO_TYPE_ID, T1.DATE_BEFORE as DATE_BEFORE
	,toInt32(round(SUM(CNT_ORD))) as CNT_ORD
FROM tmp_cnt_promo_before_1 AS T1
GROUP BY T1.STORE_LOCATION_ID, T1.PROMO_TYPE_ID, T1.DATE_BEFORE
),

tmp_cnt_promo_before_3 as (
SELECT DISTINCT T1.STORE_LOCATION_ID as STORE_LOCATION_ID, T1.PROMO_TYPE_ID as PROMO_TYPE_ID
	,toStartOfMonth(T1.DATE) as DATE_BEFORE
	,toInt32(COUNT(DISTINCT(T1.POS_ID))) AS CNT_ORD
FROM otusproj.tmp_daily_pos AS T1
WHERE T1.PROMO_TYPE_ID = 0 AND T1.PERIOD_TYPE = 'BEFORE'
GROUP BY T1.STORE_LOCATION_ID, T1.PROMO_TYPE_ID, DATE_BEFORE
)

SELECT T1.STORE_LOCATION_ID as STORE_LOCATION_ID, T1.PROMO_TYPE_ID as PROMO_TYPE_ID, T1.DATE_BEFORE as DATE_BEFORE
	,CASE WHEN T1.PROMO_TYPE_ID <> 0 THEN T1.CNT_ORD
		ELSE T2.CNT_ORD END AS CNT_ORD
FROM tmp_cnt_promo_before_2 AS T1
LEFT JOIN tmp_cnt_promo_before_3 AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
	AND T1.DATE_BEFORE = T2.DATE_BEFORE
	AND T1.PROMO_TYPE_ID = T2.PROMO_TYPE_ID