{{
    config (
      engine='MergeTree()',
      order_by=['STORE_LOCATION_ID','PROMO_TYPE_ID', 'CALDAY_CURR', 'CALDAY_BEFORE'],
	  unique_key=['STORE_LOCATION_ID','PROMO_TYPE_ID', 'CALDAY_CURR', 'CALDAY_BEFORE']
    )
}}

with tmp_cnt_ord as (
SELECT T1.STORE_LOCATION_ID as STORE_LOCATION_ID, T1.PERIOD_TYPE as PERIOD_TYPE
	,toStartOfMonth(T1.DATE) as TMP_DATE
	,COUNT(DISTINCT(T1.POS_ID)) as CNT_ORD
FROM otusproj.tmp_daily_pos AS T1
GROUP BY T1.STORE_LOCATION_ID, T1.PERIOD_TYPE, TMP_DATE
),

tmp_cnt_promo_before_11 as (
SELECT T1.STORE_LOCATION_ID as STORE_LOCATION_ID, T1.DATE_BEFORE as DATE_BEFORE
	,SUM(CNT_ORD) as CNT_ORD
FROM otusproj.tmp_cnt_promo_before AS T1
GROUP BY STORE_LOCATION_ID, DATE_BEFORE
),

tmp_cnt_total_before as (
SELECT T1.STORE_LOCATION_ID as STORE_LOCATION_ID
	,T1.TMP_DATE as CALDAY_BEFORE
	,date_add(YEAR, 1, T1.TMP_DATE) as CALDAY_CURR
	,minus(T1.CNT_ORD,T2.CNT_ORD) as CNT_ORD
FROM tmp_cnt_ord AS T1
INNER JOIN tmp_cnt_promo_before_11 AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
	AND T1.TMP_DATE = T2.DATE_BEFORE
	AND T1.PERIOD_TYPE = 'BEFORE'
),

tmp_cnt_promo_curr_1 as (
SELECT STORE_LOCATION_ID, DATE_CURR
	,SUM(CNT_ORD) AS CNT_ORD
FROM otusproj.tmp_cnt_promo_curr AS T1
GROUP BY STORE_LOCATION_ID, DATE_CURR
),

tmp_cnt_total_curr as (
SELECT T1.STORE_LOCATION_ID as STORE_LOCATION_ID
	,date_sub(YEAR, 1, T1.TMP_DATE) as CALDAY_BEFORE
	,T1.TMP_DATE AS CALDAY_CURR
	,minus(T1.CNT_ORD,T2.CNT_ORD) AS CNT_ORD
FROM tmp_cnt_ord AS T1
INNER JOIN tmp_cnt_promo_curr_1 AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
	AND T1.TMP_DATE = T2.DATE_CURR
	AND T1.PERIOD_TYPE = 'CURR'
)

SELECT
	if(TT_BEF.CALDAY_CURR>TT_CUR.CALDAY_CURR,TT_BEF.CALDAY_CURR,TT_CUR.CALDAY_CURR) as CALDAY_CURR
	, if(TT_BEF.CALDAY_BEFORE>TT_CUR.CALDAY_BEFORE,TT_BEF.CALDAY_BEFORE,TT_CUR.CALDAY_BEFORE) as CALDAY_BEFORE
	, -1 AS PROMO_TYPE_ID
	, if(TT_BEF.STORE_LOCATION_ID>TT_CUR.STORE_LOCATION_ID,TT_BEF.STORE_LOCATION_ID,TT_CUR.STORE_LOCATION_ID) as STORE_LOCATION_ID
	, TT_BEF.CNT_ORD as CNT_ORD_BEFORE
	, TT_CUR.CNT_ORD as CNT_ORD_CURR
FROM tmp_cnt_total_before AS TT_BEF
FULL JOIN tmp_cnt_total_curr AS TT_CUR 
	ON TT_BEF.STORE_LOCATION_ID = TT_CUR.STORE_LOCATION_ID
	AND TT_BEF.CALDAY_BEFORE = TT_CUR.CALDAY_BEFORE
	AND TT_BEF.CALDAY_CURR = TT_CUR.CALDAY_CURR
