{{
    config (
      engine='MergeTree()',
      order_by=['STORE_LOCATION_ID', 'PROMO_TYPE_ID', 'CALDAY_BEFORE', 'CALDAY_CURR'],
	  unique_key=['STORE_LOCATION_ID', 'PROMO_TYPE_ID', 'CALDAY_BEFORE', 'CALDAY_CURR']
    )
}}

with tmp_daily_pos_curr_1 as (
SELECT 
	T1.STORE_LOCATION_ID as STORE_LOCATION_ID
	, T1.PRODUCT_ID as PRODUCT_ID
	, T1.PROMO_TYPE_ID as PROMO_TYPE_ID
	, date_sub(YEAR, 1, T1.DATE) as TMP_CALDAY_BEFORE
	, T1.DATE as TMP_CALDAY_CURR
	, SUM(T1.SALES_QTY) as SALES_QTY
	, SUM(T1.COST) as COST
	, SUM(T1.REVENUE) as REVENUE
	, SUM(T1.VAT) as VAT
FROM otusproj.tmp_daily_pos AS T1
INNER JOIN otusproj.tmp_daily_pos_flg AS C
	ON T1.PRODUCT_ID = C.PRODUCT_ID
	AND T1.STORE_LOCATION_ID = C.STORE_LOCATION_ID
	AND toStartOfMonth(T1.DATE) = C.DATE_CURR
WHERE T1.PERIOD_TYPE = 'CURR'
GROUP BY T1.STORE_LOCATION_ID
	, T1.PRODUCT_ID
	, T1.PROMO_TYPE_ID
	, TMP_CALDAY_BEFORE
	, TMP_CALDAY_CURR
),

tmp_daily_pos_curr_2 as (
SELECT
	STORE_LOCATION_ID
	,PROMO_TYPE_ID
	,toStartOfMonth(TMP_CALDAY_BEFORE) as CALDAY_BEFORE
	,toStartOfMonth(TMP_CALDAY_CURR) as CALDAY_CURR
	,SUM(T1.SALES_QTY) as SALES_QTY
	,SUM(T1.COST) as COST
	,SUM(T1.REVENUE) as REVENUE
	,SUM(T1.VAT) as VAT
	,SUM(T1.REVENUE)/SUM(T1.SALES_QTY) as PRICE_UNIT
	,SUM(T1.COST)/SUM(T1.SALES_QTY) as COST_UNIT
FROM tmp_daily_pos_curr_1 AS T1
WHERE T1.SALES_QTY > 0
GROUP BY STORE_LOCATION_ID
	, PROMO_TYPE_ID
	, CALDAY_BEFORE
	, CALDAY_CURR
)

SELECT T1.*
	,T2.CNT_ORD as CNT_ORD
FROM tmp_daily_pos_curr_2 AS T1
INNER JOIN otusproj.tmp_cnt_promo_curr AS T2
	ON T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
	AND T1.PROMO_TYPE_ID = T2.PROMO_TYPE_ID
	AND T1.CALDAY_CURR = T2.DATE_CURR
