{{
    config (
      engine='MergeTree()',
      order_by=['CALDAY_CURR', 'PROMO_TYPE_ID', 'STORE_LOCATION_ID'],
	  unique_key='CALDAY_CURR'
    )
}}

with tmp_daily_pos_ext as (
SELECT
	  if(TT_BEF.CALDAY_BEFORE>TT_CUR.CALDAY_BEFORE, TT_BEF.CALDAY_BEFORE, TT_CUR.CALDAY_BEFORE) as CALDAY_BEFORE
	, if(TT_BEF.CALDAY_CURR>TT_CUR.CALDAY_CURR, TT_BEF.CALDAY_CURR, TT_CUR.CALDAY_CURR) as CALDAY_CURR
	, if(TT_BEF.PROMO_TYPE_ID>TT_CUR.PROMO_TYPE_ID, TT_BEF.PROMO_TYPE_ID, TT_CUR.PROMO_TYPE_ID) as PROMO_TYPE_ID
	, if(TT_BEF.STORE_LOCATION_ID>TT_CUR.STORE_LOCATION_ID, TT_BEF.STORE_LOCATION_ID, TT_CUR.STORE_LOCATION_ID) as STORE_LOCATION_ID
	, TT_BEF.SALES_QTY as SALES_QTY_BEFORE
	, TT_CUR.SALES_QTY as SALES_QTY_CURR
	, TT_BEF.COST as COST_BEFORE
	, TT_CUR.COST as COST_CURR
	, TT_BEF.REVENUE as REVENUE_BEFORE
	, TT_CUR.REVENUE as REVENUE_CURR
	, TT_BEF.VAT as VAT_BEFORE
	, TT_CUR.VAT as VAT_CURR
	, TT_BEF.CNT_ORD as CNT_ORD_BEFORE
	, TT_CUR.CNT_ORD as CNT_ORD_CURR
	, TT_BEF.PRICE_UNIT as PRICE_UNIT_BEFORE
	, TT_CUR.PRICE_UNIT as PRICE_UNIT_CURR
	, TT_BEF.COST_UNIT as COST_UNIT_BEFORE
	, TT_CUR.COST_UNIT as COST_UNIT_CURR
FROM otusproj.tmp_daily_pos_before AS TT_BEF
FULL JOIN otusproj.tmp_daily_pos_curr AS TT_CUR 
	ON TT_BEF.STORE_LOCATION_ID = TT_CUR.STORE_LOCATION_ID
	AND TT_BEF.PROMO_TYPE_ID = TT_CUR.PROMO_TYPE_ID
	AND TT_BEF.CALDAY_BEFORE = TT_CUR.CALDAY_BEFORE
	AND TT_BEF.CALDAY_CURR = TT_CUR.CALDAY_CURR
),

tmp_daily_pos_ext_cor as (
SELECT 
	CALDAY_CURR
	,CALDAY_BEFORE
	,PROMO_TYPE_ID
	,STORE_LOCATION_ID
	,toInt64(round(SALES_QTY_BEFORE)) as SALES_QTY_BEFORE
	,toInt64(round(SALES_QTY_CURR)) as SALES_QTY_CURR
	,toFloat64(round(COST_BEFORE,2)) as COST_BEFORE
	,toFloat64(round(COST_CURR,2)) as COST_CURR
	,toFloat64(round(COST_UNIT_BEFORE)) as COST_UNIT_BEFORE
	,toFloat64(round(COST_UNIT_CURR)) as COST_UNIT_CURR
	,toFloat64(round(REVENUE_BEFORE)) as REVENUE_BEFORE
	,toFloat64(round(REVENUE_CURR)) as REVENUE_CURR
	,toFloat64(round(PRICE_UNIT_BEFORE)) as PRICE_UNIT_BEFORE
	,toFloat64(round(PRICE_UNIT_CURR)) as PRICE_UNIT_CURR
	,toFloat64(round(VAT_BEFORE)) as VAT_BEFORE
	,toFloat64(round(VAT_CURR)) as VAT_CURR
	,toInt32(CNT_ORD_BEFORE) as CNT_ORD_BEFORE
	,toInt32(CNT_ORD_CURR) as CNT_ORD_CURR
FROM tmp_daily_pos_ext 
UNION DISTINCT
SELECT 
	CALDAY_CURR
	,CALDAY_BEFORE
	,PROMO_TYPE_ID
	,STORE_LOCATION_ID
	,0 as SALES_QTY_BEFORE
	,0 as SALES_QTY_CURR
	,toFloat64(0) as COST_BEFORE
	,toFloat64(0) as COST_CURR
	,toFloat64(0) as COST_UNIT_BEFORE
	,toFloat64(0) as COST_UNIT_CURR
	,toFloat64(0) as REVENUE_BEFORE 
	,toFloat64(0) as REVENUE_CURR
	,toFloat64(0) as PRICE_UNIT_BEFORE
	,toFloat64(0) as PRICE_UNIT_CURR
	,toFloat64(0) as VAT_BEFORE
	,toFloat64(0) as VAT_CURR
	,toInt32(CNT_ORD_BEFORE) as CNT_ORD_BEFORE--mb * -1
	,toInt32(CNT_ORD_CURR) as CNT_ORD_CURR--mb * -1
FROM otusproj.tmp_correction_cnt_ord
)

SELECT
	  T1.CALDAY_CURR as CALDAY_CURR 
	, T1.CALDAY_BEFORE as CALDAY_BEFORE 
	, T1.PROMO_TYPE_ID as PROMO_TYPE_ID
	, CASE WHEN PROMO_TYPE_ID = -1
			THEN 'правка'
			WHEN PROMO_TYPE_ID = 0
			THEN 'без промо'
			ELSE T3.PROMO_TYPE_NM 
	END as PROMO_TYPE_NM
	, T1.STORE_LOCATION_ID as STORE_LOCATION_ID
	, T2.STORE_LOCATION_NM as STORE_LOCATION_NM
	, T2.STORE_LOCATION_ID as STORE_LOCATION_FORMAT_ID
	, T2.STORE_LOCATION_LVL_NM2 as STORE_LOCATION_LVL_NM2
	, T1.SALES_QTY_BEFORE as SALES_QTY_BEFORE
	, T1.SALES_QTY_CURR as SALES_QTY_CURR
	, T1.COST_BEFORE as COST_BEFORE
	, T1.COST_CURR as COST_CURR
	, T1.COST_UNIT_BEFORE as COST_UNIT_BEFORE
	, T1.COST_UNIT_CURR as COST_UNIT_CURR
	, T1.REVENUE_BEFORE as REVENUE_BEFORE
	, T1.REVENUE_CURR as REVENUE_CURR
	, T1.PRICE_UNIT_BEFORE as PRICE_UNIT_BEFORE
	, T1.PRICE_UNIT_CURR as PRICE_UNIT_CURR
	, T1.VAT_BEFORE as VAT_BEFORE
	, T1.VAT_CURR as VAT_CURR
	, T1.CNT_ORD_BEFORE as CNT_ORD_BEFORE 
	, T1.CNT_ORD_CURR as CNT_ORD_CURR 
	, T2.STORE_OPEN_DT as STORE_OPEN_DT
	, CASE WHEN toStartOfMonth(T2.STORE_OPEN_DT) > T1.CALDAY_BEFORE THEN 0 ELSE 1 END AS OPEN_FLG 
FROM tmp_daily_pos_ext_cor as T1
INNER JOIN otusproj.dds_store_location as T2
	on T1.STORE_LOCATION_ID = T2.STORE_LOCATION_ID
LEFT JOIN otusproj.tmp_promo_type as T3
	on T1.PROMO_TYPE_ID=T3.PROMO_TYPE_ID